### ISSUE TITLE
Leaves iptables rule after stopping

### ISSUE THREAD

**Issue by paulb-opusvl** [NHAS/wag#1]
Very nice.

I'm just testing it out and picked one small issue. When stopping, it leaves one iptables rule behind. So next time you start you get another one, and another one, etc.

```shell
-A INPUT -i wg0 -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -i wg0 -p tcp -m tcp --dport 8080 -j ACCEPT
```

**Comment by NHAS** [comment]
Hi there, 
Thanks! 

Seems that when I start the iptables part, its adding an additional rule (and not removing it). 

Thanks for pointing this out! Latest commit should fix this.
