### ISSUE TITLE
SaveConfig is not enough

### ISSUE THREAD

**Issue by NHAS** [NHAS/wag#10]
Need to make it so that when each peer is added/removed that the change is synced to the disk.

**Comment by paulb-opusvl** [comment]
What does this relate to?

**Comment by paulb-opusvl** [comment]
Oops, clicked too early...

What does this relate to?

I ask because I had a situation where I registered a user incorrectly and figured a way to remove them from the db. It left behind the wg config, so I did a wg set wg0 peer XXX remove

**Comment by NHAS** [comment]
Could you define "left behind the wg config", as `./wag devices -del -username <blah>` should delete both the user and the wireguard peer. 

You can see this from the live running `sudo wg`

**Comment by NHAS** [comment]
`SaveConfig` is a wg-quick config directive that *should* save the wireguard config on shutdown or shutdown of the wireguard interface. 
Unfortunately, this doesnt seem to save state well enough as I recently had a VM power off and it wiped the wireguard config. 

Luckily wag records the ip and public key of the peers, so its easy enough to create. But definitely dont like waking up to users not being able to connect.

**Comment by NHAS** [comment]
Essentially this is just a reminder for me to sync the config on every change of peer. 

This will get done after I finish the hot upgrading (so you dont have to stop the vpn to deploy a new version of wag) which is currently being tested on unstable.

**Comment by paulb-opusvl** [comment]
That's a good catch... not for you, but certainly for me :)

Hot upgrades sounds awesome.

**Comment by NHAS** [comment]
Yep just finalising the work now. Its basically 90% there just needs testing now. So go ham, but I wouldnt use it for users at the moment. Had an case of it failing open, which was a tad worrying

**Comment by NHAS** [comment]
This should now be resolved with work on unstable branch
