### ISSUE TITLE
Cannot connect to server ui or 8080 for config

### ISSUE THREAD

**Issue by codechirag123** [NHAS/wag#124]
So I created the VPN server as private server with no public IP. but for the VPN tunnel at UDP port 51820 I created a Global accelerator so I can successfully connect to the VPN. 

However in the new version of Wag v7.3.2 I facing an issue where after connecting to the VPN tunnel I cannot access the Wag UI. Both the ports 8080 and 9000(UI) are opened in the Security group to VPC's CIDR range. 

So technically, it should be accessible which is also possible in older version of wag.

Everything else in the VPC is accessed fine but not the VPN server itself.

Can anyone please help me with this?
Here's the config

```
{
    "Proxied": false,
    "NAT": null,
    "HelpMail": "<my-email>",
    "Lockout": 5,
    "ExternalAddress": "<my-external-domain>",
    "MaxSessionLifetimeMinutes": 1440,
    "SessionInactivityTimeoutMinutes": 60,
    "ManagementUI": {
        "ListenAddress": ":9000",
        "Enabled": true
    },
    "Webserver": {
        "Public": {
            "ListenAddress": ":8080"
        },
        "Tunnel": {
            "Port": "80"
        }
    },
    "Authenticators": {
        "Issuer": "duve",
        "Methods": [
            "totp"
        ],
        "DomainURL": "",
        "OIDC": {
            "IssuerURL": "",
            "ClientSecret": "",
            "ClientID": ""
        },
        "PAM": {
            "ServiceName": ""
        }
    },
    "Wireguard": {
        "DevName": "wg0",
        "ListenPort": 51820,
        "PrivateKey": "<My-private-key>",
        "Address": "10.1.4.1/24",
        "MTU": 1420
    },
    "DatabaseLocation": "devices.db",
    "Acls": {
        "Groups": {
            "group:admin": [
                "user"
            ]
        },
        "Policies": {
            "group:admin": {
                "Mfa": [
                    "172.19.0.0/16"
                ],
                "Allow": [
                    "172.19.0.0/16"
                ]
            }
        }
    }
}
```

**Comment by NHAS** [comment]
Sorry, this seems like a support request rather than a feature or bug report. 

I am not currently able to provide free support as it is often quite time intensive. 
Hopefully you can sort this out!

**Comment by NHAS** [comment]
If you do find this is a bug in wag feel free to reopen it.

**Comment by codechirag123** [comment]
I believe this is a bug as I was able to successfully connect in the old version but in the new version I cannot with the same config.

**Comment by NHAS** [comment]
I can see from your config this isn't a bug. You don't have ExposePorts defined,  so iptables is blocking traffic to the management UI.
