### ISSUE TITLE
Problems with Beta version

### ISSUE THREAD

**Issue by Mariaab1** [NHAS/wag#125]
Hello again!

I've downloaded the beta version by cloning the repository to test the "deny" rules

But I've found the following problems, I don't know if it's due to  my lack of knowledge or because it's a beta version 🤔

![image](https://github.com/NHAS/wag/assets/79700199/752e949c-db5c-45e6-898b-1caa2020c32c)

Right after running "make" there is a problem with the paths of the "embed.go" file, certainly the directory structure is different:

![image](https://github.com/NHAS/wag/assets/79700199/ab15d1bf-385d-43c7-a288-ccb5a0278cfd)

Both "js" and "css" are inside "src": 

![image](https://github.com/NHAS/wag/assets/79700199/48788e7d-7485-410c-8f9d-72455dcacd2c)

Whereas "vendor" is not  🤔: 

![image](https://github.com/NHAS/wag/assets/79700199/2e0f5e7d-382c-4df4-ade9-4b29ca7c7d32)

(Could it be because of dependencies that I don't have?)

If I set the paths file like this, I can run the "make":

![image](https://github.com/NHAS/wag/assets/79700199/fb3e3083-f2c9-4eb8-8011-c367cc5cd8a8)

Once the config.json is created, when I try to start the program using it, it behaves as if I had run it with the "-join" option for a cluster instead of the "-config" option:

![image](https://github.com/NHAS/wag/assets/79700199/fa9e92bc-0887-440c-853e-f08edb0a8483)

![image](https://github.com/NHAS/wag/assets/79700199/cf31f881-2080-4104-9437-a2689c35bb5b)

However, if for instance I specify a file that does not exist, it does detect it 🔍

![image](https://github.com/NHAS/wag/assets/79700199/a89c40cb-ca18-47a1-bd6d-9106adacdaa2)

I am certainly lost in this matter :( 

Any help would be appreciated, thank you very much! 💐

**Comment by NHAS** [comment]
There have been changes to the make file so that just doing `make` on its own will just build the go binary. But not the npm/web ui. 

Try:
```sh
make release
```

Instead. 

For the rest of your issue, your `config.json` probably doesnt have the `TLSManagerListenURL` option set in the Clustering section. As noted here in the example:

```json
...
    "Clustering": {
        "ClusterState": "new",
        "ETCDLogLevel": "error",
        "Witness": false,
        "TLSManagerListenURL": "https://wag.server:3434"
    },
...
```

**Comment by Mariaab1** [comment]
Hello,

Thanks for the quick reply,

You were right about running "make release" instead of "make".

However, it wasn't that easy cause I was missing headers in the linux kernel to run clang, plus I'm in a virtualised environment (Proxmox), here's a little summary in case someone else is facing the same problem:

![image](https://github.com/NHAS/wag/assets/79700199/60f60b2e-b898-40a7-b108-bbc553d03ab4)

`cat >> /etc/apt/sources.list`

`deb http://download.proxmox.com/debian/pve **YOUR_DISTRO** pve-no-subscription` 

`wget https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg`

`apt update`

`apt install proxmox-headers-$(uname -r)`

`ln -s   /usr/include/x86_64-linux-gnu/asm/ /usr/include/asm`

Finally, you were also right about the cluster, I had omitted the whole object because in the last release it had worked without it.

In any case, thank you very much, it's working now!  🥳🎉
