### ISSUE TITLE
routes.go#L36 on make

### ISSUE THREAD

**Issue by 111blackeagle111** [NHAS/wag#16]
https://github.com/NHAS/wag/blob/66fc1b2ef127948e2b7cf152e0caa2e74bdc59db/router/routes.go#L36

└─# make
BPF_CLANG=clang BPF_CFLAGS='-O2 -g -Wall -Werror' go generate ./...
go: downloading golang.zx2c4.com/wireguard/wgctrl v0.0.0-20220916014741-473347a5e6e3
go: downloading github.com/mattn/go-sqlite3 v1.14.15
go: downloading golang.zx2c4.com/wireguard v0.0.0-20220407013110-ef5c587f782d
go: downloading github.com/pquerna/otp v1.3.0
go: downloading github.com/cilium/ebpf v0.9.3
go: downloading github.com/mdlayher/netlink v1.6.2
go: downloading github.com/coreos/go-iptables v0.6.0
go: downloading golang.org/x/sys v0.0.0-20221013171732-95e765b1cc43
go: downloading golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4
go: downloading github.com/boombuler/barcode v1.0.1-0.20190219062509-6c824513bacc
go: downloading github.com/josharian/native v1.0.0
go: downloading github.com/mdlayher/socket v0.2.3
go: downloading golang.org/x/net v0.0.0-20221014081412-f15817d10f9b
go: downloading golang.org/x/sync v0.0.0-20220923202941-7f9b1623fab7
go: downloading github.com/mdlayher/genetlink v1.2.0
Error: exec: "llvm-strip": executable file not found in $PATH
exit status 1
router/routes.go:36: running "go": exit status 1
make: *** [Makefile:12: .generate_ebpf] Error 1

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc $BPF_CLANG -cflags $BPF_CFLAGS bpf xdp.c -- -I headers

it is wrong to attack the two // but just detach them and the make continues.
// go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc $BPF_CLANG -cflags $BPF_CFLAGS bpf xdp.c -- -I headers

bye bye

**Comment by NHAS** [comment]
That line is important for the whole project as it generates the object code for the eBPF program. 
You just havent installed the llvm packages for your distribution

**Comment by 111blackeagle111** [comment]
router/routes.go:36: running "go": exit status 1
make: *** [Makefile:12: .generate_ebpf] Error 1

I spaced the two // from the go and redid the make. Then everything went smoothly
If you feel that this is not a general problem, please close the issue
:) tnx

**Comment by NHAS** [comment]
I understand what you have done. 
If you make any changes to the `xdp.c` file, your changes will not be included as that line re-generates the eBPF object code. The only reason it still works for you is because I include the compiled objects in the git repo. 

The problem is that you havent installed the llvm packages by your last error, you may also need to install clang or just generally run `go get ./...`
