### ISSUE TITLE
package embed is not in GOROOT

### ISSUE THREAD

**Issue by paulb-opusvl** [NHAS/wag#2]
I put this on a different system to test some more. Previously it was on Alpine Linux 3.15, now I put it on Debian 11

I'll confess to being a `go` novice.

```shell
$ go build                                 
router/bpf_bpfel.go:9:2: package embed is not in GOROOT (/usr/lib/go-1.15/src/embed)
```

I suspect it is a difference in the `go` package on the two environments.

```shell
$ doas apk add go
$ go version
go version go1.17.10 linux/amd64
```
Versus

```shell
$ sudo apt install golang
$ go version  
go version go1.15.15 linux/amd64
```

**Comment by NHAS** [comment]
Howdy, 

Unfortunately the embed functionally in golang was  [added in go1.16](https://blog.jetbrains.com/go/2021/06/09/how-to-use-go-embed-in-go-1-16/), and since wag uses a bunch of embedding it will only work on go >= 1.16

**Comment by paulb-opusvl** [comment]
Thanks I realised that and moved to a later `go`.

Might be worth adding into the prereqs in the readme.

Also, a small doc change

```shell
cp example_config config.json
```

should be

```shell
cp example_config.json config.json
```
