### ISSUE TITLE
Feature request: session expiration based on src-ip/src-port

### ISSUE THREAD

**Issue by grisu-cl** [NHAS/wag#20]
hi,

first, thanks for the project ... i like wireguard - and MFA on top of it ... great

do you think it would be a good idea to use the client-src-IP/port as a parameter to timeout a session?
means: if client-src-ip or client-src-port changes a re-authentication is requrired

the solution with a time-based session-timout ... hmm ...

**Comment by NHAS** [comment]
The project already uses client-src-IP & port to expire sessions.
