### ISSUE TITLE
[Feature Request] Support `PresharedKey`

### ISSUE THREAD

**Issue by ak-aozasa** [NHAS/wag#26]
Hi,

Thank you for a great product. It is very helpful for me!

Would it be possible for to extend wag to support `PresharedKey`?
`PresharedKey` is a standard feature of wireguard.
ref.: https://man7.org/linux/man-pages/man8/wg.8.html#CONFIGURATION_FILE_FORMAT

I would like to use `PresharedKey` to improve security.

**Comment by NHAS** [comment]
Yep I can look at supporting this. 

I am currently planning on supporting this by just randomly generating it per device. At the moment there is a big effort to get a web ui developed, but after I've completed that work I'll get this done as its relatively easy :)

**Comment by ak-aozasa** [comment]
Thank you for your consideration.

I am looking forward to it being implemented.

**Comment by NHAS** [comment]
Just leaving a note here, I've completed this feature on the unstable branch and will do a release when I can bundle it in to some of the other small feature requests.

**Comment by ak-aozasa** [comment]
@NHAS Thank you for implementing my request!

**Comment by NHAS** [comment]
No problem. As thanks you can pull down the latest version and make sure it isn't horribly buggy :p
