### ISSUE TITLE
NGINX Reverse Proxy for https does not work (no way to configure ip tables rules from wag config file) 

### ISSUE THREAD

**Issue by bluecraank** [NHAS/wag#27]
Hello,

so i try to get https in front of the MFA Portal, but a soon as i change it, no connection can be established. 

tcpdump show traffic, but no response from portal.

Is there any limitation built into your webserver?

**Comment by NHAS** [comment]
Hi there, wag does support being used behind a reverse proxy.

You will need to enable the proxy optioknin the configuration file and add the X-Forwarded-For headers. I haven't tested it myself.


Your issue may be cause by ip tables rules that wag adds that disallow input to any port on the host other than the Web server port (and ip) and icmp (ping)

I would suggest using wag directly to do your TLS for the vpn mfa page at least (the config has options for cert and key path for tls)

**Comment by bluecraank** [comment]
This is my config

server {
    listen 443 ssl http2;
    ssl_certificate /etc/ssl/certs/vpnserver.pem;
    ssl_certificate_key /etc/ssl/private/vpnserver.key.pem;
    server_name mfa**;
    location / {
        #proxy_set_header Host $host;
        #proxy_set_header X-Forwarded-Host $host;
        #proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Real-IP $remote_addr;
        #proxy_set_header X-Forwarded-Proto $scheme;
        #add_header Front-End-Https on;
        #add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        proxy_pass https://localhost:8080/;
        #client_max_body_size 10M;
    }
}

**Comment by bluecraank** [comment]
And this is the wag config (not the full)

`
{
    "Proxied": true,
    "Lockout": 5,
    "HelpMail": "it@doepke.de or 049311806/666",
    "MaxSessionLifetimeMinutes": 600,
    "SessionInactivityTimeoutMinutes": 60,
    "ExternalAddress": "doepke-norden.ddns.net",
    "DatabaseLocation": "devices.db",
    "Issuer": "Doepke WireGuard",
    "DNS": ["192.168.100.78","192.168.100.98"],
    "Webserver": {
        "Public": {
            "ListenAddress": "127.0.0.1:8080"
        },
        "Tunnel": {
            "ListenAddress": "127.0.0.1:8081"
        }
    },
    "Wireguard": {
        "DevName": "wg0",
        "ListenPort": 51820,
        "PrivateKey": "WKUvfll+NHVmleitSMrxI56iQfBQGxuqaFtLju8L8FY=",
        "Address": "10.40.20.1/24",
        "MTU": 1280,
        "PersistentKeepAlive": 25
    },
`

**Comment by bluecraank** [comment]
This is the wag config (a piece of it)

```
{
    "Proxied": true,
    "Lockout": 5,
    "HelpMail": "123456789",
    "MaxSessionLifetimeMinutes": 600,
    "SessionInactivityTimeoutMinutes": 60,
    "ExternalAddress": "example.com",
    "DatabaseLocation": "devices.db",
    "Issuer": "WireGuard",
    "DNS": ["192.168.100.1","192.168.100.2"],
    "Webserver": {
        "Public": {
            "ListenAddress": "127.0.0.1:8080"
        },
        "Tunnel": {
            "ListenAddress": "127.0.0.1:8081"
        }
    },
    "Wireguard": {
        "DevName": "wg0",
        "ListenPort": 51820,
        "PrivateKey": "hidden",
        "Address": "10.40.20.1/24",
        "MTU": 1280,
        "PersistentKeepAlive": 25
    }
}
```

**Comment by bluecraank** [comment]
Hey,

yeah my issue is that the port is blocked on the server because of wag

Is there any chance to allow Port 443 and the other ports for the webservers?

**Comment by bluecraank** [comment]
Okay, i added in iptables.go an additional entry for allowing 443
This works :D

Maybe there should be the option, if key "Proxied" is set to true, then u can also set "ProxyPort" if Proxy is on same server

**Comment by NHAS** [comment]
Yep I 100% agree with you there, it should give you the option of adding an arbitrary port (or just ip tables rules in general)

I'll add this to the list of things to do. Web ui is almost done! So I'll be getting to them soon

**Comment by NHAS** [comment]
Sweet, I've fixed this on the unstable branch, by adding a config directive `ExposePorts` which should allow people to go and expose whatever ports they like on the VPN host. 

I'll be doing a round up release today or tomorrow after I've tested everything.

**Comment by bluecraank** [comment]
Nice work man! Nice to see activity on this project. I will test it on ubuntu.
