### ISSUE TITLE
flag provided but not defined: -config

### ISSUE THREAD

**Issue by paulb-opusvl** [NHAS/wag#3]
When starting from a different directory, I'm unable to specify a path to the `config.json`.

```shell
$ /opt/wag/wag start --config ./config.json
flag provided but not defined: -config
Usage of start:
Error:  flag provided but not defined: -config
Usage of start:
  Run the wag server on the settings found in config.json
```

But the help details how:

```shell
$ /opt/wag/wag -h                          
			Wag
Adds 2fa and device enrolment to wireguard deployments.

Supported commands: start, cleanup, reload, registration, devices, firewall
All commands require:
  -config string
    Configuration file location (default "./config.json")
```

**Comment by NHAS** [comment]
Ah yep, I've come across this before but I am in the middle of a deployment so havent had time to fix.

**Comment by NHAS** [comment]
Just a small note, for the golang `flag` package, it takes arguments as `-config` rather than `--` (although the config problem is separate to this)

**Comment by NHAS** [comment]
This is now fixed in the latest release.

**Comment by paulb-opusvl** [comment]
I was trying `-` and `--` just to be sure.

But thanks for your efforts.
