### ISSUE TITLE
Config Generated Wrong DNS

### ISSUE THREAD

**Issue by paulb-opusvl** [NHAS/wag#33]
```text
$ sudo ./wag version                                       
remote
Version: v4.1.1-1-gf055b4c
Hash: 853da9fd51248b4cb68c9418b6e3fc871b7dad492521b5b7bb02689c14d04633
```

I just registered a new user, and it generated the config for me.

```ini
[Interface]
PrivateKey = SuperSecretKey
DNS = 10.10.6.254/32
Address = 192.168.254.27

[Peer]
Endpoint =  82.123.123.123:51821
PresharedKey = SuperSecretKey
PublicKey = SecretKey
AllowedIPs = ...
PersistentKeepAlive = 10
```

I wasn't paying attention, and then wondered why it never used resolvd and I could not do any DNS lookups.

It stuck a bogus `/32` onto the DNS entry. Removed this and DNS now works.

**Comment by NHAS** [comment]
Ah thanks for finding that. I don't use the dns directive myself.

I'll give that a fix today

**Comment by NHAS** [comment]
Done a little release enjoy :)
