### ISSUE TITLE
Possibility to customize MFA Portal

### ISSUE THREAD

**Issue by bluecraank** [NHAS/wag#36]
At the moment, i have to download source and customize template files.

Maybe it is possible, that the compiled version looks for a folder where templates are in

**Comment by NHAS** [comment]
How are you customising the template files? 

At the moment I'm looking to not add new features for a while and make the design and feel of the various UI elements of wag more consistent. So I cant promise that this will be something Im going to do any time soon, or at all. 

More context is always useful tho :)

**Comment by bluecraank** [comment]
We have a specific design and would like to do the same with the MFA Portal. Therefore it would be great if you could specify in the config what the template files are to overwrite the HTML

**Comment by NHAS** [comment]
Im planning on wrapping this up into the 6.x.x release Im doing soon. Is allowing you to define your own CSS for it enough? Or would you like complete control (as thats a bit harder for me to make)

**Comment by bluecraank** [comment]
Hello,

i would prefer full control. You could create a template folder and check if there are any files for overwriting design, this should not be so hard to make

**Comment by NHAS** [comment]
Yep I have a method in mind. You can look forward to this in the next couple days all things going well

**Comment by NHAS** [comment]
I have added this in the latest pre-release. Please give it a shot and tell me if this suites, if it does I'll do a full release. 

https://github.com/NHAS/wag/releases/tag/v6.1.1-pre-release

**Comment by bluecraank** [comment]
How to use css and more?

**Comment by NHAS** [comment]
Please read the documentation.

**Comment by bluecraank** [comment]
I did, at the moment u can add javascript / css files to template folder. Addressing css to other sources is not allowed (style-src webserver restriction) So the only way is inline css?

**Comment by bluecraank** [comment]
Oh even inline styles not working :(

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' fonts.googleapis.com". Either the 'unsafe-inline' keyword, a hash ('sha256-QK8bSv1dlnwrOBpQEtdh0AtJ1yALgA+MYljY7NkQMGU='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

**Comment by NHAS** [comment]
Yep that's how csps work.

I'll look at adding a css and js folders in the template directory.

**Comment by bluecraank** [comment]
Yeah, i now building wag myself and added the style files into the static folder.
