### ISSUE TITLE
Whether to operate wireguard with routing or natting should be adjustable

### ISSUE THREAD

**Issue by bluecraank** [NHAS/wag#39]
## iptables.go line 39
```
	err = ipt.Append("nat", "POSTROUTING", "-s", config.Values().Wireguard.Range.String(), "-j", "MASQUERADE")
	if err != nil {
		return err
	}
```

Me again,

it would be great if you could set whether the traffic should be routed or natted, since routing can later be used to clearly identify which request comes from which client

## example config.json
DEFAULT: false
```json
"routing": "false"
```
If routing is true, just skip that code

Hope it is understandable.

**Comment by NHAS** [comment]
Yep that makes sense and I like it. Being able to turn on and off batting makes a lot of sense.


I'll add that.

**Comment by NHAS** [comment]
This is now on the unstable branch for you to try out

**Comment by bluecraank** [comment]
Thanks! I am currently testing

**Comment by bluecraank** [comment]
Works perfectly!
