### ISSUE TITLE
Allow internal devices to access wireguard client

### ISSUE THREAD

**Issue by bluecraank** [NHAS/wag#40]
## Problem
So far everything is running, I only have the problem that, apart from the server, no other devices can ping WireGuard peers or generally no communication can be established

## My solution
```
        err = ipt.Append("filter", "FORWARD", "-i", "ens160", "-o", "wg0", "-j", "ACCEPT")
        if err != nil {
                return err
        }
```

So i added this code in iptables.go **before** line 29 to allow incoming traffic from interface where everything else is connected to wg0 interface

## General solution
There should be a way to allow this, but i do not know really how. How i solved it allows EVERYTHING from internal, thats may not be the best way

**Comment by paulb-opusvl** [comment]
Whilst no strictly what you want, we use it to ssh onto clients using `ProxyJump` in the ssh config.

```
Host remoteSystem
  ProxyJump witegaurdServer
```
As long as we can ssh, we can tunnel pretty much anything else.

**Comment by NHAS** [comment]
So. If I'm understanding you correctly, you have your wag server acting as a gateway to an internal network.

In that internal network you want hosts to be able to route through the wag server and talk to the wireguard peers?

You will have to write a wag rule for that of course.

I do see what you mean and I'll have a think about how best to implement that.

**Comment by NHAS** [comment]
Honestly, I was doing a think, and I believe this was just an oversight on my behalf as I dont use wag like this. Im more than happy to just add a blank forward from all interfaces to your wireguard peer interfaces. 

Obviously this will still be governed by the wag rules. 

E.g something like 
```sh
iptables -A FORWARD -o wg0 -j ACCEPT
```

**Comment by NHAS** [comment]
I've put this in unstable branch just for fun. Please give it a go, Im trying to think if this adds any risk or not. 

Also @paulb-opusvl I dont suppose you've had time to do anything with the docs page? Do you need a run through or something, could always grab your <social media> and have a chat if you need!

**Comment by bluecraank** [comment]
This works as expected!

**Comment by NHAS** [comment]
Awesome. I'll be doing a roll up release soonish to have that as a main branch feature.
