### ISSUE TITLE
Policies on expiration 

### ISSUE THREAD

**Issue by ComponentClass** [NHAS/wag#47]
Hey there! I came across this project and it fits my goals almost to a T for what I am looking for! I just had one question (hoping this is already how this works and not additional features) 

I aim to have custom expiration  based on the policy / ip/port being connected to. This is to allow say, VPNing in to access my email server to require MFA each time, but VPNing in to route to my diagram software to only need it once a month. 

I do not believe this is currently possible, but wanted to check!

**Comment by NHAS** [comment]
Howdy!

Glad you like wag and that it's working for ya.

Unfortunately what you've described isn't something wag does (and I'm not sure how I'd make that work from a UX perspective)

Hopefully you can still keep using it though!
