### ISSUE TITLE
Restarting in docker doesn't always work

### ISSUE THREAD

**Issue by bvanwiggen** [NHAS/wag#57]
When the docker container is restarted I get the following error:
`unable to create control socket: listen unix /tmp/wag.sock: bind: address already in use`

I expect wag.sock not to be cleared when the container exits, because when I create the container it starts without any issue. Within a docker environment the wag.sock can be cleared on startup since there won't be any other instance using it.

**Comment by NHAS** [comment]
Ahhhhhh yes, so whats happening here is that wag has a signal handler that only catches SIGINT rather than SIGTERM which is what docker uses when killing them (iirc). 

THis is super annoying and I'll look at getting that sorted! Thanks for the report, gives me motivation to get it done.

**Comment by NHAS** [comment]
Hm I actually cant replicate this, can you give me the version and how you're using the docker image?
