### ISSUE TITLE
Confusing typo in README.md in the Ranges section.

### ISSUE THREAD

**Issue by TheraNinjaCat** [NHAS/wag#60]
The README.md file around line [440](https://github.com/NHAS/wag/blob/947175f9cea8b68c25583e4c8094dd7818cdd13f/README.md?plain=1#L440C1-L441C1) is talking about defining ranges with the low port first then the high port, however the example on line 440 references `53-23/tcp`, which has the high port first.

**Comment by NHAS** [comment]
Oops!
