### ISSUE TITLE
Expose port range

### ISSUE THREAD

**Issue by marulitua** [NHAS/wag#66]
Thank you for your amazing work.

I need to expose a port range `10000-20000`.
But currently we don't support [range](https://github.com/NHAS/wag/blob/947175f9cea8b68c25583e4c8094dd7818cdd13f/internal/config/config.go#L549).
So what I do instead, is created 10001 entries
```
    "DatabaseLocation": "devices.db",
    "ExposePorts": [
        "10000/udp",
        "10001/udp",
        .
        .
        .
        "19997/udp",
        "19998/udp",
        "19999/udp",
        "20000/udp"
    ],
    "ExternalAddress": "xxx.xxx.xxx.xxx",
    "HelpMail": "support@mailcom",
    "Lockout": 5,
```
 But turn out with all these entries, WAG need a long time to set up iptables.
```
root@ubuntu-jammy:/home/vagrant# time systemctl restart wag
                                                                                                                                       
real    3m0.423s
user    0m0.000s
sys     0m0.005s
```
I think it would be great if we support range instead of have a lot of entries.
Is that possible to have this feature ?
IMHO Iptables itself accept port range.

![image](https://github.com/NHAS/wag/assets/2355307/67ea1917-9ce6-4328-b7bd-532388e574bc)

**Comment by NHAS** [comment]
Hi.

Wag currently does support ranges for ports.
And it doesn't use iptables to do the allowing.

**Comment by NHAS** [comment]
An example from the readme: 192.168.1.1 22-1024/tcp 23-53/any: Format

**Comment by marulitua** [comment]
The thing is I want to expose ports on the VPN server to the client.
So, I don't need to set `ExposePorts` port if I add `Policies` rules ?

**Comment by NHAS** [comment]
Oh yes you're right and I totally skim read this. Sorry!

**Comment by emaruli** [comment]
As this feature is good for new newcomer, let me try to contribute to this uber cool piece of software

**Comment by NHAS** [comment]
That's so awesome! Thanks!

Can I suggest forking from the unstable branch when you make your changes?

**Comment by marulitua** [comment]
I see, will do
