### ISSUE TITLE
Site to site

### ISSUE THREAD

**Issue by IsaacBreuer** [NHAS/wag#69]
Just a question 
How do I get this to work as site to site.
I have finally configured it, works great from client to server or client to any device on server lan
But cannot get ot to work from other devices on lan to see client.
Tried adding route to wg0 on server , but getting messgae required key not available when doing raceroute

**Comment by NHAS** [comment]
Hi there.


Wag is not really designed to be used as a site to site vpn.

I would suggest using manual wireguard (such as wg-quick and a profile) to set up another wireguard tun device and the routes you require from your wag server  to your external site.

**Comment by IsaacBreuer** [comment]
The rules are setup always and client can access all devices on servers lan, 

My issue is with other devices on servers lan snnot see client, 
Look like the WG interface does not allow traffic from eh0

**Comment by NHAS** [comment]
For servers in another lan to access clients you will have to turn off natting on wag and manually insert iptables rules and routes in order to allow routing to your clients.
