### ISSUE TITLE
Change totp secret from gui

### ISSUE THREAD

**Issue by IsaacBreuer** [NHAS/wag#70]
I have tried using totp with a hardware token that has a pre programed seed as secret,

What I did so far was setting up a regular totp with app, than opening the sql db and changing just the secret to my hardware token, worked out great, ust asking if it's possible to do the same from gui.

**Comment by NHAS** [comment]
You can do this by hitting "reset Mfa" after selecting a user

**Comment by IsaacBreuer** [comment]
No, that will just create a new random secret, but won't allow me to specify a secret

**Comment by NHAS** [comment]
Ah right. No, wag does not have a way of doing this

**Comment by IsaacBreuer** [comment]
Wag certification has access to the db, so it would be positive to just as an input and update the record,  just as I did it manually. 

It's not a big deal, icjust,wanted tobshare that I have used it with a pre programed token .
