### ISSUE TITLE
Wag host IP is not accessible

### ISSUE THREAD

**Issue by vnovichek** [NHAS/wag#73]
Hi, thanks again for the project.
The issue is very similar to https://github.com/NHAS/wag/issues/67 but instead of DNS I have troubles connecting to the wag host itself, e.g. wag is installed on 192.168.5.25 and after authentication I can ping 192.168.5.25 but I can't ssh into it or something. Tried to add "192.168.5.25" or "192.168.5.25 22/tcp" to the mfa block but didn't help.

```
...
    "Acls": {
        "Policies": {
            "*": {
                "Mfa": [
                    "192.168.5.0/24"
                ],
                "Allow": [
                ]
...
```

Please advise. Thanks.

**Comment by NHAS** [comment]
https://github.com/NHAS/wag/issues/71
