### ISSUE TITLE
Custom templates not working

### ISSUE THREAD

**Issue by bluecraank** [NHAS/wag#76]
Hello,

i try to access my custom css and javascript.

https://server.com/custom/custom_style.css
"404 page not found"

Filestructure:

templates
- static
- - custom_style.css
- - css
- - - custom_style.css

config.json
```
"MFATemplatesDirectory": "templates"
```

Whats is wrong?

**Comment by NHAS** [comment]
Ah thats quite frustrating, it seems i've forgotten to strip the path prefix when using `FileServer`

**Comment by NHAS** [comment]
As a temporary work around I think if you make your path:
```
"MFATemplatesDirectory": "templates"
```

With the structure:

```
templates/custom/static/
```

It should work, but I'll change that to be more logical
```

**Comment by bluecraank** [comment]
Seems to work

**Comment by bluecraank** [comment]
But your workaround seems not to work. Need to wait for your new wag build on master

**Comment by bluecraank** [comment]
Works!
