### ISSUE TITLE
Restore server-side persistent keepalive for logged-in users for a specified time frame

### ISSUE THREAD

**Issue by vnovichek** [NHAS/wag#78]
Prior to v7.3.2 and https://github.com/NHAS/wag/issues/64, this feature was convenient—I could put my laptop to sleep and resume work in the morning without going through the authentication process again. Reintroducing this capability for logged-in users within a defined time window would be quite handy.

**Comment by NHAS** [comment]
Honestly, kudos to whatever device is handling your NAT for keeping its entry alive with only mono-directional traffic.
As for adding it back, I think I'll just add it to the config file as that seems easiest!

**Comment by NHAS** [comment]
Ah  never marked this as on unstable. 

This has been brought back as the `ServerPersistentKeepAlive` configuration open for you!

**Comment by NHAS** [comment]
Obviously this hasnt made it into a main release just yet. But soon
