### ISSUE TITLE
unable to render change password page: template: menus.html:192:56: executing "menus.html" at <.Message>: range can't iterate over

### ISSUE THREAD

**Issue by bluecraank** [NHAS/wag#79]
Hi, this error appears if i try to navigate to change password

WAG Version
Wag v7.3.0-1-g93c403c
`unable to render change password page: template: menus.html:192:56: executing "menus.html" at <.Message>: range can't iterate over`

also tried on
Wag v7.3.2-2-g8f3870g
`
unable to render change password page: execute [templates/menus.html templates/change_password.html]: template: menus.html:193:56: executing "menus.html" at <.Message>: range can't iterate over`

**Comment by NHAS** [comment]
I am running `Wag v7.3.2-6-gd0888f2` and this is not an issue for me.

**Comment by NHAS** [comment]
Ah yes I see the problem. Cheers!

**Comment by bluecraank** [comment]
Works!

**Comment by NHAS** [comment]
Awesome glad to hear it
