### ISSUE TITLE
connection issues with MS Edge browser, Firefox OK

### ISSUE THREAD

**Issue by uplight-dev** [NHAS/wag#82]
I've been getting constantly, every few minutes or so, this client-side log:

```
2023-12-21 23:03:59.082: [TUN] [...] Keypair 1 destroyed for peer 1
```

After this, the session gets destroyed and I need to relogin with hardware key.
Since WAG is wrapping wireguard itself, I've no idea how to run commands like `wg` on server to show/investigate the connectivity issues.

Is there a way to investigate still?

Thanks!

**Comment by NHAS** [comment]
Hm, I havent seen that on my deployments unfortunately. If you're using the docker container version of wag you can jump in with `docker exec -it <container> /bin/bash` and have a look,

Otherwise you may need to install the `wg-tools` on a base metal install. 


Not really sure how to help you as each deployment is quite different and it might be devices in the way of wag and the internet.

**Comment by uplight-dev** [comment]
Thanks for trying, no worries!

Actually I'm not sure this is the cause, but I was using MS Edge browser to login to WAG. Since I passed to Firefox I didn't encounter the issue ... yet.

Can the browser cause the client to be kicked-out of WAG and have to relogin?

**Comment by uplight-dev** [comment]
Do you know if the session is maintained client-side or server-side? I tried to clear cookies but it keeps me logged-in. So I'm not sure which session-mechanism is being used.

**Comment by NHAS** [comment]
> Can the browser cause the client to be kicked-out of WAG and have to relogin?

In later versions there is a logout url on the bottom of the page. But in earlier versions no, you could force it by locking/unlocking an account. 

> Also, with `wg-tools` you meant to try using wireguard standalone, without WAG, is that it? Or can I use it in collaboration with WAG?

You can use wg-tools in conjunction with wag, its all wireguard so things can still see and interact with the WG device that wag sets up. Just if you change things wag may get unhappy. 

> Do you know if the session is maintained client-side or server-side?

Its all server side based on your network address and client wg public key.

**Comment by uplight-dev** [comment]
if it's all server-side, can there be anything at all related to MS Edge that could cause a random connection close?

**Comment by uplight-dev** [comment]
actually it happened in Firefox also, but after about 45 minutes. I'll try with wg-tools and/or a bare wireguard install.
