### ISSUE TITLE
QR-Code instead of Download wg0.conf

### ISSUE THREAD

**Issue by bluecraank** [NHAS/wag#88]
For mobile devices like android or iOs, it's easier and faster using qr-code to scan and get config instead of downloading config.

Maybe its possible to decide "okay this is a mobile phone so please show qr-code"

**Comment by NHAS** [comment]
This feature already exists

**Comment by bluecraank** [comment]
Oh nice!! I did not see that.

**Comment by muff10** [comment]
Has QR code been removed in newer version? I am not able to get qr code when quering api for wg0.conf file.

**Comment by NHAS** [comment]
The QR code was removed in later versions as it seemed no one was using it.
