### ISSUE TITLE
Access dns-server fully after mfa

### ISSUE THREAD

**Issue by krambrock** [NHAS/wag#90]
I've got two dns-servers that I would like to access without mfa:

    "Wireguard": {
        "DevName": "wg0",
        "ListenPort": 5555,
        "PrivateKey": "*** MYKEY ***",
        "Address": "10.1.2.1/24",
        "MTU": 1420,
        "DNS" : ["192.168.2.1", "192.168.2.254"]
    }

And the complete /24 network with mfa:

    "Acls": {
        "Policies": {
            "*": {
                "Mfa": [
                    "192.168.2.0/24"
                ]
            }
        }
    }

I can only access 192.168.2.1 and 192.168.2.254 on port 53 with and without mfa. That makes sense, because the public rule for 192.168.2.1 and 192.168.2.254 gernerated from my dns-entries is more specifig. So I tried this:

    "Acls": {
        "Policies": {
            "*": {
                "Mfa": [
                    "192.168.2.0/24",
                    "192.168.2.1/32",
                    "192.168.2.254/32"
                ]
            }
        }
    }

Leads to this diagnostics:

    "user": {
        "Policies": [
            "10.1.2.1/32 policy [public(20) any/any]",
            "192.168.2.1/32 policy [mfa(16) any/any public(20) 53/any]",
            "192.168.2.254/32 policy [mfa(16) any/any public(20) 53/any]",
            "192.168.2.0/24 policy [mfa(16) any/any]"
        ],
        "Devices": [
            {
                "LastPacketTimestamp": 0,
                "Expiry": 0,
                "IP": "10.1.2.2",
                "Authorized": false
            }
        ],
        "AccountLocked": 0
    }

"mfa(16) any/any public(20) 53/any" looks perfect to me but does not work out. I cannot access 192.168.4.1 on port 53 without mfa. After mfa I can access them (but that is not what I want). Probably I am doing something wrong ...

**Comment by NHAS** [comment]
I don't know what you're trying to accomplish here.

You said your initial configuration worked just fine to allow you non-mfa access to your dns server.

Then changed it to over write the rule from an allow policy to an Mfa policy for your dns servers?

Also 192.168.4.1 isn't in your regular regardless and I'm assuming that's a typo.


Due to limited time on my behalf I cannot offer in-depth support. Unless it relates to a bug in the codebase itself, without financial support.

Thanks!

**Comment by krambrock** [comment]
It is been a typo, sorry, I corrected it. I thought accessing the dns-server on port 53 without mfa and on all ports with mfa might be a regular requirement/bug.

**Comment by krambrock** [comment]
I found out how to solve it (in case anybody has the same problem). Having this:
```
"Wireguard": {
    "DevName": "wg0",
    "ListenPort": 5555,
    "PrivateKey": "*** MYKEY ***",
    "Address": "10.1.2.1/24",
    "MTU": 1420,
    "DNS" : ["192.168.2.1", "192.168.2.254"]
}
``` 

You need this ACLs:
```
"Acls": {
	"Policies": {
		"*": {
			"Mfa": [
				"192.168.2.0/24",
				"192.168.2.1/32 1-52/any 54-100000/any icmp",
				"192.168.2.254/32 1-52/any 54-100000/any icmp"
			]
		}
	}
}
``` 

Leading to this diagnostics:
```
{
    "user": {
        "Policies": [
            "10.1.2.1/32 policy [public(20) any/any]",
            "192.168.2.1/32 policy [mfa(8) 1-52/any mfa(8) 54-34464/any mfa(16) any/icmp public(20) 53/any]",
            "192.168.2.254/32 policy [mfa(8) 1-52/any mfa(8) 54-34464/any mfa(16) any/icmp public(20) 53/any]",
            "192.168.2.0/24 policy [mfa(16) any/any]"
        ],
        "Devices": [
            {
                "LastPacketTimestamp": 0,
                "Expiry": 0,
                "IP": "10.1.2.2",
                "Authorized": false
            }
        ],
        "AccountLocked": 0
    }
}
```

It's a bit suprising to me and maybe not most elegant but it works. The dns-server is accessable via dns only without mfa and is fully accessable with mfa.
