### ISSUE TITLE
Enable Discussions and Wiki for this repository

### ISSUE THREAD

**Issue by eeldivad** [NHAS/wag#91]
This is an amazing project.  I think adding discussions and wiki will allow the community to grow it further as we can then collaborate with each other more easily.  The wiki will allow us to share more examples, templates, etc with each other.

**Comment by NHAS** [comment]
Howdy! Thanks for the compliment.

I didn't even think of that but I can do!

Also soon we'll have proper high availablity!

**Comment by eeldivad** [comment]
That would be so amazing!  I was just talking to my team yesterday about Wag and we are worried about losing service if our Wag server is down.  Can't wait for HA!  HA all the way!

One thing I would post to "Discussions" once you enable it is:  How do we see the transfer stats for byes sent/received?
It's not really an "Issue" but something the community can answer too so you can focus on fixing bugs and adding other cool features like HA.

**Comment by NHAS** [comment]
To see that you'd have to just use `sudo wg` on the box you're on. You can open that as a feature request, as it wouldnt take much to add. 

Just noting that the HA work is still on-going so you might not get a release with that for quite a while

**Comment by NHAS** [comment]
Sweet both of those are enabled. Neither of them has content :P
